"""Regenerate build artefacts that need the version baked in.

Run before PyInstaller and Inno Setup so the exe metadata, installer filename,
and About dialog all match version.py. Called from build.bat.
"""

from __future__ import annotations

from pathlib import Path

from version import __version__

HERE = Path(__file__).parent


def _parse_quadruple(version_str: str) -> tuple[int, int, int, int]:
    """Turn '1.2.3' into (1, 2, 3, 0) — Windows wants four components."""
    parts: list[int] = []
    for piece in version_str.split('.'):
        digits = ''.join(c for c in piece if c.isdigit())
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])  # type: ignore[return-value]


def write_pyinstaller_version_info() -> None:
    quad = _parse_quadruple(__version__)
    quad_str = '.'.join(str(n) for n in quad)
    text = f"""VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={quad!r},
    prodvers={quad!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName',      u''),
         StringStruct(u'FileDescription',  u'MailWeave - Email Organiser & Exporter'),
         StringStruct(u'FileVersion',      u'{quad_str}'),
         StringStruct(u'InternalName',     u'MailWeave'),
         StringStruct(u'LegalCopyright',   u''),
         StringStruct(u'OriginalFilename', u'MailWeave.exe'),
         StringStruct(u'ProductName',      u'MailWeave'),
         StringStruct(u'ProductVersion',   u'{quad_str}')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 1200])])
  ]
)
"""
    (HERE / 'version_info.txt').write_text(text, encoding='utf-8')


def write_inno_version_include() -> None:
    text = (
        '; Auto-generated by sync_version.py — do not edit by hand.\n'
        f'#define AppVersion "{__version__}"\n'
    )
    (HERE / '_version.iss').write_text(text, encoding='utf-8')


if __name__ == '__main__':
    write_pyinstaller_version_info()
    write_inno_version_include()
    print(f'sync_version: wrote version_info.txt and _version.iss for {__version__}')
